acme_blogs:
    type: rest
    prefix: /api
    resource: "@AcmeBlogBundle/Resources/config/routes.yml"

# acme_blog:
#     resource: "@AcmeBlogBundle/Controller/"
#     type:     annotation
#     prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#REST

# rest :
#   type : rest
#   resource : "routing_rest.yml"
#   prefix : /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
