# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # role_hierarchy:
    #     ROLE_ADMIN:       ROLE_USER
    #     ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        LoginExampleBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: LoginExampleBundle:User }

    firewalls:
        main:
            pattern: /
            anonymous: true
        user:
            pattern: ^/user/
            # anonymous: true
            form_login:
                # The route name that the login form submits to
                check_path: security_login_check
                login_path: security_login_form
            logout:
                # The route name the user can go to in order to logout
                path: security_logout
        api:
            pattern: ^/api/
            # anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'



    access_control:
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        # allow anonymous API - if auth is needed, it's handled in the controller
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
