# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    jwt_token_authenticator:
        class: LoginExampleBundle\Security\JwtTokenAuthenticator
        autowire: true
    api_exception_subscriber:
        class: LoginExampleBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory', '@logger']
        tags:
            - { name: kernel.event_subscriber }
    api.response_factory:
        class: LoginExampleBundle\APIBase\ResponseFactory
