<?php

namespace LoginExampleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrangeRepository extends EntityRepository
{
}
